# Generated by Django 4.1.3 on 2022-11-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.PositiveSmallIntegerField()),
                ('completed', models.DateField()),
                ('level', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
